### ISSUE TITLE
Passing CLI arguments in Flask App

### ISSUE THREAD

**Issue by ricknichols84** [minimaxir/gpt-2-simple#101]
Hi, I'm trying to pass CLI arguments from GPT-2 simple into a Flask app. For example:

gpt_2_simple generate --temperature 1.0 --nsamples 20

Does anyone know how to pass these arguments/flags (e.g. --) into Flask? Help appreciated.

**Comment by minimaxir** [comment]
There's really no reason to use the CLI in Flask; just import the package directly.

If you really need to use the CLI, use the `subprocess` package.
