### ISSUE TITLE
Tensor is not element of this graph.

### ISSUE THREAD

**Issue by marcoaleixo** [minimaxir/gpt-2-simple#118]
Actually I trying to make a API Flask using your package.
But I don't want to load the model for every request, so, I'm trying to load sess when Flask is initializing and just use the "gpt2.generate" but I'm receiving the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3796, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3875, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("Placeholder:0", shape=(1, ?), dtype=int32) is not an element of this graph.
```

Are possible to use this package without load to every request?
I'm using python 3.6

**Comment by minimaxir** [comment]
You need to load the model as the Flask app loads, instead of loading the model on request. (see a similar approach used for a [Starlette app](https://github.com/minimaxir/gpt-2-cloud-run/blob/master/app.py) in gpt-2-cloud-run: the concept is the same for Flask).

**Comment by marcoaleixo** [comment]
Well, worked with your gpt2-cloud-run.
Thank you!
