### ISSUE TITLE
Why 1023 in this code?

### ISSUE THREAD

**Issue by ty5491003** [minimaxir/gpt-2-simple#123]
https://github.com/minimaxir/gpt-2-simple/blob/e6afb284c194667f98ad38c7fa89352cdce8b841/gpt_2_simple/gpt_2.py#L435
From this code, we can see that the maxlen of  the generative data is 1023 tokens, no matter how we adjust the '--length' parameter when generating. So i want to ask why set a constant 1023 in this code?

**Comment by minimaxir** [comment]
The original GPT-2 model is fixed at a context window of 1024; if you go over, it'll error.

The fix is a sliding windows approach which is in #87  but it needs testing.

**Comment by ty5491003** [comment]
Got it, thx.

**Comment by v-limu** [comment]
![image](https://user-images.githubusercontent.com/54055206/66725642-a5f6ca80-ee66-11e9-985f-acdfa3db1c18.png)
