### ISSUE TITLE
Is there a parameter for human prompt?

### ISSUE THREAD

**Issue by lenhhoxung86** [minimaxir/gpt-2-simple#128]
Hi,
Thank you for this impressive work.
I read your blog and I saw a picture showing the text completion given a prompt. In the demo app Talk to Transformer, there is also a text field for human prompt.
I wonder if there is a parameter for human prompt?
I think it is necessary in case we want to generate text for a specific topic.
Thanks.

**Comment by minimaxir** [comment]
The prompt in Talk to Transformer functions the same as the `prefix`.

**Comment by ChemGuy88** [comment]
Great question and answer. If it helps anyone, try this:

```python
results = gpt2.generate(sess, prefix="What is your favorite color?")
```

Following the nomenclature used in the [README tutorial](https://github.com/minimaxir/gpt-2-simple#readme).
