### ISSUE TITLE
Add 1558M to GPU finetuning blacklist

### ISSUE THREAD

**Issue by WAUthethird** [minimaxir/gpt-2-simple#135]
Title says it all.

**Comment by minimaxir** [comment]
I actually future-proofed it in anticipation of the `1558M` release.: https://github.com/minimaxir/gpt-2-simple/blob/master/gpt_2_simple/gpt_2.py#L147

Need to check if that still works.

**Comment by WAUthethird** [comment]
I'm getting some weird errors in Colaboratory (non-OOM) when loading the model.

**Comment by minimaxir** [comment]
Tracking 1558M issues in #136

**Comment by enochlev** [comment]
Colab now has a100 40gb GPU available for $1.30/hour.
1558 may now be able to work
