### ISSUE TITLE
Finetuning: fresh vs. latest

### ISSUE THREAD

**Issue by woctezuma** [minimaxir/gpt-2-simple#14]
When finetuning a model, I would like a clarification for `fresh `vs. `latest`.

I thought that:

- `fresh` would start from the original GPT-2 model,
- `latest` would start from the previous checkpoint.

However, I am a bit confused right now (#13). Is it rather that:

- both start from the previous checkpoint, if available,
- otherwise from the original GPT-2 model,

and that:

- `fresh` would perform `steps` iterations,
- `latest` would perform the remaining iterations so that the total number of iterations is `steps`.

**Comment by minimaxir** [comment]
> both start from the previous checkpoint, if available,

That shouldn't be right, in my testing `fresh` always started from the base model. (did you reset the Python session before rerunning?)

> `latest` would perform the remaining iterations so that the total number of iterations is steps.

That behavior seems like a bug but should be an easy fix.

**Comment by woctezuma** [comment]
Thank you for the clarifications. I will let you know if I notice a bug. Do not take into account my first post.

**Comment by woctezuma** [comment]
For some reason, I had not taken into account your important note about fine-tuning...

> IMPORTANT NOTE: If you want to rerun this cell, restart the VM first (Runtime -> Restart Runtime).

**Comment by minimaxir** [comment]
Fixed in 0.3.1
