### ISSUE TITLE
CUDA gpu setting

### ISSUE THREAD

**Issue by MiaYangheeKim** [minimaxir/gpt-2-simple#143]
How can I set the gpu number to run the model? 
The model automatically run all of the gpus I have (Total 4 gpus), but I want to use only 2 gpus and specify the number when run the model.
I tried to find the line to modify the gpu setting in the codes, but failed.
I'd really appreciate if you let me know the solution.
Thank you.

**Comment by MiaYangheeKim** [comment]
solved it

**Comment by AlexDunmow** [comment]
What did you do to solve it?
