### ISSUE TITLE
How can I ensure specific keywords are included in the generated text (like you have in the Reddit example in production)?

### ISSUE THREAD

**Issue by zacheberhart** [minimaxir/gpt-2-simple#158]
I'd like to do something similar and I'm wondering how exactly you did it. Do you generate a bunch and choose those which have that keyword? Or do you create special tokens which have the keywords (something like: [KEYWORD] keyword1, keyword2 [RESPONSE] ... )

I'm referring to this example: https://minimaxir.com/apps/gpt2-reddit/

**Comment by zacheberhart** [comment]
That worked. Thanks for the great library!

**Comment by DGaffney** [comment]
@zacheberhart can you provide a gist of how you were able to make that work? Would be interested to see it.

**Comment by zacheberhart** [comment]
@DGaffney So far I've only managed to get decent results from one keyword, but I did it almost exactly as I mentioned in the initial question (and I expect no problems with multiple keywords, I just need to build the dataset):

```
<|startoftext|>[INPUT_TOKEN] car [RESPONSE] I drove a car to work . <|endoftext|>
<|startoftext|>[INPUT_TOKEN] dog [RESPONSE] We took our dog for a walk . <|endoftext|>
etc, etc...
```

I have a dataset of  ~400k samples and found the best results at around 350-450 epochs of fine-tuning. Building the dataset is obviously the trickiest part because you'll need to encode the text so that the model isn't overfitting on common keywords. I have a specific use case in mind so my encoding script isn't the most efficient, but I can share that if interested.

**Comment by vishwasgpai** [comment]
Hey, @zacheberhart  Can u please share the encoding script. When I tried with my dataset of about 300 samples with 30 epoch it overfitted a lot. Secondly, I added **[INPUT_TOKEN]** in train set and in generated text, only training words were coming not new words.

**Comment by kawa23** [comment]
@zacheberhart @minimaxir @vishwasgpai 
Hi, I'm also interested at generated text  with keywords, but had no idea how to implement it.
Any help would be greatly appreciated.
