### ISSUE TITLE
Other examples using gpt-2-simple

### ISSUE THREAD

**Issue by woctezuma** [minimaxir/gpt-2-simple#16]
For info, I have used your Python module in these two repositories:

-   [generate fake reviews for Steam games](https://github.com/woctezuma/sample-steam-reviews-with-gpt-2),
-   [generate store descriptions for fake Steam games](https://github.com/woctezuma/sample-steam-descriptions).

I am not trying to advertise these, but I thought I would let you know.

**Comment by minimaxir** [comment]
Those are good examples! Thanks for letting me know! :) (also I might have use for your `steamreviews` package)

BTW it's not easy for me to see closed issues: an email is better!
