### ISSUE TITLE
How can I get the input and output text in a dict instead?

### ISSUE THREAD

**Issue by youssefavx** [minimaxir/gpt-2-simple#190]
As you know, when you do 

`gpt2.generate(sess, length=250, temperature=0.7, prefix="Example", nsamples=5, batch_size=5)`

It returns something like this: 

Example 
Continuation 
Continuation 

==============

Example
Continuation 
Continuation 

Is it possible to just get this in a dictionary or list instead? Meaning something like this: 

`{'Example':['Continuation Continuation Continuation'], 'Example':['Continuation Continuation']}`

?

**Comment by minimaxir** [comment]
You can specify `return_as_list=True`, and use regexes to extract given start words.

This specific use case is more niche (albeit something I had in the roadmap for my next package), but mostly out-of-scope here.

**Comment by youssefavx** [comment]
Good enough for me! Thanks so much!
