### ISSUE TITLE
UnicodeEncodeError during training

### ISSUE THREAD

**Issue by logicpeters** [minimaxir/gpt-2-simple#192]
In the middle of training, and also occasionally during generation, the code errors out with the following exception:

UnicodeEncodeError: 'charmap' codec can't encode character '\u203b' in position 1198: character maps to <undefined>

The character/position varies.   It comes from the print(text) statement in generate_samples() (line 298 in dev branch).   Should I pre-process all of my input files to utf-8 encoding before running them through?   Most are utf-8, but a few of them have ascii encoding, windows-1252 and iso-8859-1 encoding.

**Comment by minimaxir** [comment]
Weird; the input files are loaded as UTF-8 so that shouldn't happen.

You should probably preprocess the files regardless though.
