### ISSUE TITLE
355M model specified shape (1024, 768) and found shape (1024, 1024)

### ISSUE THREAD

**Issue by papee** [minimaxir/gpt-2-simple#195]
Hi all,

I tryed to train the 355M model, everything is going fine for training.
Then I tryed to generate some text but got this error:
ValueError: Trying to share variable model/wpe, but specified shape (1024, 768) and found shape (1024, 1024).

My generate script:

sess = gpt2.start_tf_sess()
gpt2.load_gpt2(sess, run_name=355M)
gpt2.generate(sess, 
                length=200,
                temperature=0.5, 
                nsamples=1,
                batch_size=1
                )

My model hparams.json:
{
  "n_vocab": 50257,
  "n_ctx": 1024,
  "n_embd": 1024,
  "n_head": 16,
  "n_layer": 24
}

**Comment by papee** [comment]
Ok my bad had to set the model:

gpt2.generate(sess, 
model_name="355M",
length=200,
temperature=0.5,
nsamples=1,
batch_size=1
)

everything works fine.

**Comment by minimaxir** [comment]
yep
