### ISSUE TITLE
Issue Finetuning 1558M in Google Collab

### ISSUE THREAD

**Issue by lilcorpse** [minimaxir/gpt-2-simple#201]
Recently I tried finetuning the 1558M in collab, everything went well except for the fact that the output it generated only had some slight variance from the dataset. I'm wondering why this is? Is it because the dataset is too small for this large model?

**Comment by minimaxir** [comment]
tl;dr yes. The only reason you should be finetuning the 1558M model is if you have a _lot_ of data.

**Comment by jmarsil** [comment]
@minimaxir question to add onto this, what would be considered a lot of data, 1G sized text file?

**Comment by minimaxir** [comment]
Yes, 1GB would be enough data.

"A lot of data" more implies that you'll get underwhelming results with like 1 MB of data.
