### ISSUE TITLE
Getting alot of data that is just copied from my input set

### ISSUE THREAD

**Issue by lemiesz** [minimaxir/gpt-2-simple#240]
Trying to generate tweets based on a input set of tweets. What I am seeing is that lot of the generated data ends up just being repeated tweets word for word.  

Im training on <1000 tweets. So I dont think its overfitting, but could it be that the lack of data is causing the repeats?

**Comment by rbewoor** [comment]
Not sure if relevant. But have you tried playing around with top_k and temperature parameters? Using say high temp=0.95 and top_k = 0 or 40?

**Comment by lemiesz** [comment]
Yah actually playing around with those led to better tweets. Also, just training on a bigger data set overall removed these issues.
