### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero error when fine tuning 

### ISSUE THREAD

**Issue by alex-golub99** [minimaxir/gpt-2-simple#246]
Hi, I'm trying to fine tune the algorithm and am having a lot of trouble, just running the code straight from the google colab notebook without modifying anything on my own, and I'm really not sure how to fix it. These are the errors I got:

`WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/gpt_2_simple/src/sample.py:17: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Loading checkpoint models/124M/model.ckpt
INFO:tensorflow:Restoring parameters from models/124M/model.ckpt
0it [00:00, ?it/s]Loading dataset...
dataset has 0 tokens
Training...

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-5-67d252685180> in <module>()
      9               print_every=10,
     10               sample_every=200,
---> 11               save_every=500
     12               )

3 frames
/usr/local/lib/python3.6/dist-packages/gpt_2_simple/gpt_2.py in finetune(sess, dataset, steps, model_name, model_dir, combine, batch_size, learning_rate, accumulate_gradients, restore_from, run_name, checkpoint_dir, sample_every, sample_length, sample_num, multi_gpu, save_every, print_every, max_checkpoints, use_memory_saving_gradients, only_train_transformer_layers, optimizer, overwrite)
    335                 for _ in range(accumulate_gradients):
    336                     sess.run(
--> 337                         opt_compute, feed_dict={context: sample_batch()})
    338                 (v_loss, v_summary) = sess.run((opt_apply, summary_loss))
    339             else:

/usr/local/lib/python3.6/dist-packages/gpt_2_simple/gpt_2.py in sample_batch()
    307 
    308     def sample_batch():
--> 309         return [data_sampler.sample(1024) for _ in range(batch_size)]
    310 
    311     if overwrite and restore_from == 'latest':

/usr/local/lib/python3.6/dist-packages/gpt_2_simple/gpt_2.py in <listcomp>(.0)
    307 
    308     def sample_batch():
--> 309         return [data_sampler.sample(1024) for _ in range(batch_size)]
    310 
    311     if overwrite and restore_from == 'latest':

/usr/local/lib/python3.6/dist-packages/gpt_2_simple/src/load_dataset.py in sample(self, length)
     81     def sample(self, length):
     82         assert length < self.total_size // len(
---> 83             self.chunks
     84         ), "Dataset files are too small to sample {} tokens at a time".format(
     85             length)

ZeroDivisionError: integer division or modulo by zero`

**Comment by minimaxir** [comment]
Are you specifying the correct text file / is the file uploaded into Colab?

**Comment by alex-golub99** [comment]
> Are you specifying the correct text file / is the file uploaded into Colab?

Oh man I had for some reason thought that the text files needed to be in the "sample_data" folder, which then was clearly not working. I have since fixed it and it seems to be working now! Thank you!!
