### ISSUE TITLE
sess returned as None type when loaded back into an environment

### ISSUE THREAD

**Issue by Travis-Barton** [minimaxir/gpt-2-simple#249]
Hello! 

This package is awesome! and it works inside the terminal ex:
` gpt_2_simple generate --temperature 0.5 --nsamples 10 --length 100 --nfiles 5 --run_name "new_run_large"`
works great

 so I know this is a python/path issue.

When I run 

```
import os

os.chdir('machine_learning_scripts/speed_test')

import tensorflow as tf

import gpt_2_simple as gpt2

sess = gpt2.start_tf_sess()

sess = gpt2.load_gpt2(sess, run_name='new_run_large')
```

sess is a nonetype and `single_text = gpt2.generate(sess, return_as_list=True, run_name='new_run_large')[0]` returns the error: 

```
Traceback (most recent call last):
  File "<input>", line 31, in <module>
  File "/home/tbarton/.conda/envs/bella/lib/python3.7/site-packages/gpt_2_simple/gpt_2.py", line 470, in generate
    out = sess.run(output, feed_dict={
AttributeError: 'NoneType' object has no attribute 'run'
```

Any idea why? The fine tuning step worked great without a hitch, and the directory 'new_run_large' is inside of the 'checkpoint' folder inside of 'speed_test'

**Comment by Travis-Barton** [comment]
Is anyone able to help me with this? I cannot progress until I can generate text from a fine-tuned model in python /:

**Comment by Tylersuard** [comment]
This one didn't work for me, I still got the same error
