### ISSUE TITLE
le 'tensorflow.python.util.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by yangboz** [minimaxir/gpt-2-simple#250]
File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/gpt_2_simple-0.7.1-py3.6.egg/gpt_2_simple/src/memory_saving_gradients.py", line 13, in <module>
AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'

any different tensorflow version number?

**Comment by Travis-Barton** [comment]
I use 1.15 and it seems to work in the command line, but see that I have another issue open so you may run into that problem.

**Comment by yangboz** [comment]
thanks, @Travis-Barton ,pip install tensorflow==1.15 it works now.
