### ISSUE TITLE
345M Directory Issue

### ISSUE THREAD

**Issue by WAUthethird** [minimaxir/gpt-2-simple#26]
When running the example code in the README.md, after executing the line that trains on my custom dataset, it comes out with this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\gpt_2_simple\gpt_2.py", line 106, in finetune
    os.path.join(checkpoint_path, file))
  File "C:\Program Files\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\117M\\hparams.json'
```
I'm trying to run with the 345M model, but it seems there's no code to automatically search in one or the other. I only have the 345M model installed. 

This is the line I am trying to run.
`gpt2.finetune(sess, 'file.txt', steps=1000)`
You'll notice that there's nothing to denote 117M or 345M, but it still looks for the file in 117M, which does not exist.

**Comment by david-sg** [comment]
Temp fix, change the 345M directory name to 117M

**Comment by minimaxir** [comment]
Sorry, you need to pass `model_name` to `finetune()` as well. Will tweak the README.

**Comment by WAUthethird** [comment]
Ah, thanks!
