### ISSUE TITLE
Error when I try to generate text from finetuned model

### ISSUE THREAD

**Issue by RokaMic** [minimaxir/gpt-2-simple#28]
I'm new to machine learning.

I get this error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-7a3554f49918> in <module>()
      1 sess = gpt2.start_tf_sess()
----> 2 gpt2.load_gpt2(sess,'run2')

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)
    846         tb = [x for x in tb if "tensorflow/python" not in x[0]][:3]
    847         raise ValueError("%s Originally defined at:\n\n%s" % (err_msg, "".join(
--> 848             traceback.format_list(tb))))
    849       found_var = self._vars[name]
    850       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable model/wpe already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/usr/local/lib/python3.6/dist-packages/gpt_2_simple/src/model.py", line 153, in model
    initializer=tf.random_normal_initializer(stddev=0.01))
  File "/usr/local/lib/python3.6/dist-packages/gpt_2_simple/gpt_2.py", line 127, in finetune
    output = model.model(hparams=hparams, X=context)
  File "<ipython-input-8-6c3e8cce67cd>", line 11, in <module>
    run_name='run2'

Any ideas how to fix this?

**Comment by minimaxir** [comment]
In the Notebook, you must restart the runtime before rerunning `load_gpt2()`.
