### ISSUE TITLE
Enhancement - Can you make the default readme generated text from terminator scripts?

### ISSUE THREAD

**Issue by johndpope** [minimaxir/gpt-2-simple#29]

**Comment by minimaxir** [comment]
Although I'm a fan of meta jokes, there are copyright issues involved with that particular request.

**Comment by johndpope** [comment]
currently retraining using your work book - thank you for your efforts + documentation.
http://www.scifiscripts.com/scripts/t2.txt

**Comment by johndpope** [comment]
https://gist.github.com/johndpope/9a6a813efa58adc674ff191c934625f6


20C     ON SARAH, her bare feet slapping the cold tiles.
	She climbs to her feet.  Moodyly, she walks toward Dyson.

				SARAH
		You got her?

	He nods.  She reaches for Silberman and we think she's going to hug him.
	She pushes him away from her and takes aim at the other hostage.
	One of them is moving quickly, pulling the other toward her.
	She aims the M-16 at the guy's head and fires.
	The other pulls the trigger.  The .45 auto slugs ricochet off the guy's body as
	he screams.
	The other guy drops, laughing.  Sarah grabs the .45 and aims it at
	Dyson's head.
	He screams and drops what he is doing, his eyes wide.
	She grabs him by the hair and slams him face down on the floor,
	smacking him behind the knees expertly with the pistol.
	He slaps her across the back of the head with the bare
	hand.  She giggles and runs off, disappearing around a corner into
	the corridor.
