### ISSUE TITLE
0 tokens when attempting to finetune using .txt

### ISSUE THREAD

**Issue by lukegalea** [minimaxir/gpt-2-simple#31]
Using the collaboratory (have not tried locally), I tried loading a normal text file and it found 0 tokens.

I've found that splitting on whitespace and turning my source file into a csv was the only way to get past this.

All of the examples reference "shakespeare.txt" but that file isn't included in the repo so I have not been able to confirm what the tool is expecting from a plaintext file.

**Comment by minimaxir** [comment]
You need to include your own file of course: the `shakespeare.txt` is a demo file of a famous dataset for training textgen models.

**Comment by woctezuma** [comment]
I think it happened to me when the text file was on my Google Drive, and I moved it, or overwritten it for some reason, yet my Colab session has not been synced correctly with your Google Drive. If that is your issue, I suggest that you get your text file on your Colab machine, because there are some weird synchronization/ghosting issues when using Google Drive for everything.

**Comment by lukegalea** [comment]
@minimaxir I tried supplying just a single text file with content (which I imagine shakespeare.txt looks like) and that resulted in "0 tokens found". 

I was hoping to look to your shakespeare file to see if you had done any special formatting (<startoftext> around things, etc??).

Converting the text file to a csv with one token per line isn't ideal as the output ends up looking like:

```
<|startoftext|>and<|endoftext|>
<|startoftext|>maybe<|endoftext|>
<|startoftext|>I<|endoftext|>
<|startoftext|>might<|endoftext|>
<|startoftext|>feel<|endoftext|>
<|startoftext|>like<|endoftext|>
<|startoftext|>I<|endoftext|>
<|startoftext|>should<|endoftext|>
<|startoftext|>have<|endoftext|>
<|startoftext|>a<|endoftext|>
```

**Comment by woctezuma** [comment]
This is not what the output would look like.

**Comment by minimaxir** [comment]
[This file](https://github.com/jcjohnson/torch-rnn/blob/master/data/tiny-shakespeare.txt?raw=true) is the `shakespeare.txt`: there is nothing special about it.

No matter how your file is formatted, the only way "0 tokens found" is if you did not provide a reference to the file. You can double check if the file is in the VM in the Files tab.

**Comment by ricknichols84** [comment]
FYI, i was getting the same 0 tokens error when i was saving the txt file inside the samples or drive folders. I noticed that when I uploaded the txt file outside of all folders, this issue went away. Don't know why this happens.

**Comment by david-sg** [comment]
I had some problems with this and a csv file- make sure to save as UTF-8, and if using excel, format the column to remove the text wrap before saving.
