### ISSUE TITLE
Importance of prepending <|startoftext|> and suffixing <|endoftext|>

### ISSUE THREAD

**Issue by woctezuma** [minimaxir/gpt-2-simple#33]
I have been using your package on a large .txt file which is a concatenation of texts (mostly reviews, and also store descriptions). However, I am unsure whether it would be important to prepend `<|startoftext|>` and append `<|endoftext|>` before concatenating the different texts.

Am I doing something wrong if I don't use these tokens?

**Comment by woctezuma** [comment]
Maybe linked to #5.

**Comment by woctezuma** [comment]
Also, do you have to add `\n` between `<|endoftext|>` and `<|startoftext|>`?

Or it does not matter?

**Comment by minimaxir** [comment]
The tokens make it much easier to use `truncate` to mass-generate texts. Additionally, `<|endoftext|>` was used in the original datasets so GPT-2 has an idea on how to handle them and therefore fine-tune them better.

The `\n` isn't strictly necessary but doesn't harm training. (and you'll have a bad time if working with small phrases and the model samples everything on one line!)
