### ISSUE TITLE
Anyone understand the code of the small model? I'm looking to hire someone!

### ISSUE THREAD

**Issue by bladedsupernova** [minimaxir/gpt-2-simple#4]
I really reallllly want to know how GPT-2 works. They gave us trained code, a Paper, and a assortment of news on the internet describing parts of it like Transformers etc.

Has anyone put the puzzle pieces together yet? Or can? I need you. This algorithm is very important in *generating research* that changes the world.

I currently hire someone to program my non-neural network program that will soon reach a somewhat close level at least with GPT-2, as I understand how text generation works on many levels. But I still should know how GPT-2 works, and I have a ton of effort to put in so it should be put into the right spot.

I'm not a mathematician or programmer and my understanding of research/AGI is working, I am learning a lot each day, but I seriously need someone to explain how GPT-2 works visually or in English.

**Comment by minimaxir** [comment]
Although more clarity behind the Transformer architecture would be appreciated, please don't use Issues for solicitation.
