### ISSUE TITLE
Replace vocab and encoder for other languages

### ISSUE THREAD

**Issue by ZheMann** [minimaxir/gpt-2-simple#47]
Currently I'm trying to train the GPT-2 345M model on columns written in the Dutch langauge. Everything seems to work pretty fine while generating samples, although the model sometimes comes up with fictional words (or partially English). Now I'm wondering if a customized vocab.bpe (based on the Dutch corpus) and an encoder (e.g. https://github.com/google/sentencepiece) would increase the results. I'm not sure about this, as the Dutch and English language are relatively similar langauges.

Thanks in advance.

**Comment by minimaxir** [comment]
You wouldn't be able to finetune the current GPT-2 models if you used a different `vocab.bpe`, and training from scratch is out of scope.
