### ISSUE TITLE
Typo in call to sample.sample_sequence()

### ISSUE THREAD

**Issue by woctezuma** [minimaxir/gpt-2-simple#49]
I cannot figure out whether [this line](https://github.com/minimaxir/gpt-2-simple/blob/873db52d79b380a79cdda0012208a105428e9306/gpt_2_simple/gpt_2.py#L352) is a typo.

```python
    output = sample.sample_sequence(
        hparams=hparams, length=length,
        start_token=enc.encoder['<|endoftext|>'] if not prefix else None,
        context=context if prefix else None,
        batch_size=batch_size,
        temperature=temperature, top_k=top_k
    )[:, 1:]
```

Specifically:

```python
start_token=enc.encoder['<|endoftext|>'] if not prefix else None,
```

Shouldn't it be the following instead?

```python
start_token=enc.encoder['<|startoftext|>'] if not prefix else None,
```

**Comment by minimaxir** [comment]
Nope, that's correct; it's how it is in the official GPT-2 code as well (because the source datasets use the `<|endoftext|>` tokens).
