### ISSUE TITLE
The first word of the prefix is trimmed to 1 character

### ISSUE THREAD

**Issue by woctezuma** [minimaxir/gpt-2-simple#5]
I did not notice this behavior in my previous tests, because the first word was "I" as in "I love" or "I hate". However, when the first word is "Please", it seems that the algorithm takes into account the whole word but only displays the first character ("P").

![Please, Valve, ](https://i.imgur.com/ko0ySCv.png)

**Comment by minimaxir** [comment]
This was a weird behavior that I couldn't isolate how it happens (and it happened when using the interactive mode in the original GPT-2 scripts). When testing, it was always a character short, but in this case it's much more characters short. Hmm.

**Comment by woctezuma** [comment]
The good news is that it is only cosmetic.

**Comment by nsankar** [comment]
Can a user input text  be used as a prefix? (say interactive mode)

**Comment by woctezuma** [comment]
> Can a user input text be used as a prefix? (say interactive mode)

Yes.

**Comment by woctezuma** [comment]
Maybe linked to #33.

**Comment by saippuakauppias** [comment]
+1 for me :(
