### ISSUE TITLE
Improved Sampling (Nucleus Sampling)

### ISSUE THREAD

**Issue by bob80333** [minimaxir/gpt-2-simple#51]
In a recent paper, they find that beam search actually does even worse than greedy search for GPT-2 117M, and they propose a new sampling method to improve text output.

[Neural Text Degradation](https://arxiv.org/abs/1904.09751)

From what I understand, it's top-k sampling, except instead of `k` tokens, it takes all tokens until probability of these tokens combined is > some parameter `p`.

Here's an example from the paper:

🗣Context: 
On days when he woke early, the president
liked to have coffee in the oval office. There was
something about watching the sky grow lighter and
lighter as you sat your pajama'd behind in the most
powerful chair in the free world, sipping marine strength
coffee, that you just couldn't achieve anywhere else.

---
💰Greedy: He'd been in the oval office for over a year
now, and he'd never been so happy to be there. He'd
been in the oval office for almost a year, and he'd never
been so happy to be there.

---
🚦BeamSearch (k=4): The President was a man of his
word. He was a man of his word. He was a man of his
word. He was a man of his word. He was a man of his
word. He was a man of his word.

---
🥄Sampling (t=1.0): You couldn't be sure if that's what
you were really doing, and If you decided to take the day
off. The president wanted you to take the day off, but he
wanted to maintain a curfew and use his influence wisely.

---
🇰Top-k Sampling (k=8): "I'm sorry, sir." "No, it's okay,
son," the president said. "I understand." "You're going
to have to make a special trip down there to get that kid.
He has no idea where he's going."

---
⚛️Nucleus Sampling (p=0.9): But that wasn't what drew
the president's attention. He'd been seated for maybe a
minute when he noticed the other man. What was the
guy doing here?

---
🗣Gold: He was therefore disagreeably surprised to find
a man in an understated grey suit sitting in that selfsame
chair sipping tea. The president turned around and went
looking for his chief of staff.

**Comment by bob80333** [comment]
Here's a sample implementation of top-k and nucleus sampling (top-p) in Pytorch:

https://gist.github.com/thomwolf/1a5a29f6962089e871b94cbd09daf317

**Comment by minimaxir** [comment]
Although neat, that's beyond the scope of this package.

**Comment by minimaxir** [comment]
Never mind, Neil Sheppard added an implementation for it:  https://github.com/nshepperd/gpt-2/commit/87fe3d7c50de78e31a0578eea7a4b34d6e8217fe

I can merge that.

**Comment by minimaxir** [comment]
Added in 0.5 as a `top_p` parameter.

**Comment by woctezuma** [comment]
I am trying to understand this example, now that v0.5 includes nucleus sampling.

I need to read about the meaning of `k=4` in BeamSearch.

However, you might be able to tell me about the temperature for top-k sampling and nucleus sampling. Is it set to 1? 0.7? Or doesn't it matter too much?

**Comment by woctezuma** [comment]
I could not find the info regarding the value of the temperature in the paper. I guess the authors chose temperature = 1, so that it has no effect on the probabilities, according to formula (4). However, I am not sure because Figure 8 relies on a temperature of 0.8.

![figure 8](https://i.imgur.com/byrsAnd.png)

In the code of this Python module, I see that the temperature is used [at this line](https://github.com/minimaxir/gpt-2-simple/blob/7dc82105f94e88770bc198016a5718517e935e8d/gpt_2_simple/src/sample.py#L71), even for nucleus sampling. So, it is good to keep in mind the number of top tokens depend on both parameters (`p` and `temperature`).

```python
            logits = next_outputs['logits'][:, -1, :] / tf.to_float(temperature)
            if top_p > 0.0:
                logits = top_p_logits(logits, p=top_p)
            else:
                logits = top_k_logits(logits, k=top_k)
            samples = tf.multinomial(
            logits, num_samples=1, output_dtype=tf.int32)
```

**Comment by minimaxir** [comment]
My interpretation is that like `top_k`, `top_p` is a constraint on the sheet craziness of the output. (which is why it might be less effective on fine-tuned datasets, but we'll see.)

**Comment by AlexanderYogurt** [comment]
Do we have a beam search implementation in this package? It is not performing as good as top-k, but maybe it's good to also include it for completeness?

**Comment by ty5491003** [comment]
@bob80333 Excuse me,  i'm a freshman in text generation domain, i've just read this paper,  i have a question that what's the meaning of  'Gold sampling' and how is it implemented? 
Thx.

**Comment by bob80333** [comment]
As I understand it, 'Gold' was the actual continuation of the text sample, aka ground truth.

**Comment by ty5491003** [comment]
I get it.  Thx. -------- 原始邮件 --------发件人： Eric Engelhart <notifications@github.com>日期： 2019年9月26日周四 11:21收件人： minimaxir/gpt-2-simple <gpt-2-simple@noreply.github.com>抄送： Yang Tian <nwu_ty@163.com>, Comment <comment@noreply.github.com>主    题： Re: [minimaxir/gpt-2-simple] Improved Sampling (Nucleus Sampling) (#51)As I understand it, 'Gold' was the actual continuation of the text sample, aka ground truth.

**Comment by ty5491003** [comment]
@bob80333 I get it, thx!
