### ISSUE TITLE
How to deal with the checkpoint folder?

### ISSUE THREAD

**Issue by pawo161** [minimaxir/gpt-2-simple#58]
First of all thank you for your contribution. 
I would like to convert generated model to tensorflow.js to use it on a website. 
Could you explain me how to deal with the output checkpoint folder?

**Comment by minimaxir** [comment]
TensorFlow.js support is way out of scope for this, not to mention a 500MB model would be impossible to deploy on it.

**Comment by jochemstoel** [comment]
I'm sorry but you are wrong. It is not impossible to get GPT-2 running with Tensorflow.js and a 500MB model is not outrageously big these days.
