### ISSUE TITLE
Why does gpt-2 work (relatively) well for the Dutch language?

### ISSUE THREAD

**Issue by ZheMann** [minimaxir/gpt-2-simple#60]
First, the generated texts are not always grammatical correct and it can be improved much more, but after finetuning the gpt-2 models (both 117M and 345M) on Dutch datasets, the majority of words are spelled correctly and also connections between sentences appear. Sometimes an English word appears in a sentence but this happens occasionally.

The Dutch and English language are obviously pretty similar, but I'm still wondering how this works as the pre-trained model is based on dictionairy files generated by solely English texts.  

I'm very curious whether someone is able to explain this to me. 

Thank you very much in advance.

**Comment by woctezuma** [comment]
GPT-2 is a zero-shot model. It is not trained with a specific language or task in mind.

> GPT-2 achieves state-of-the-art scores on a variety of domain-specific language modeling tasks. Our model is not trained on any of the data specific to any of these tasks and is only evaluated on them as a final test; this is known as the “zero-shot” setting. GPT-2 outperforms models trained on domain-specific datasets (e.g. Wikipedia, news, books) when evaluated on those same datasets.

> On other language tasks like question answering, reading comprehension, summarization, and translation, we are able to get surprising results without any fine-tuning of our models, simply by prompting the trained model in the right way (see below for examples of how we do this), though we do still fall short of state-of-the-art for specialized systems.
