### ISSUE TITLE
Finetune on 4Gb VRAM

### ISSUE THREAD

**Issue by k0a1a** [minimaxir/gpt-2-simple#63]
In order to successfully funetune 117M model I had to adjust 

> data_sampler.sample(256)

in

https://github.com/minimaxir/gpt-2-simple/blob/7dc82105f94e88770bc198016a5718517e935e8d/gpt_2_simple/gpt_2.py#L239

thanks

**Comment by minimaxir** [comment]
Yeah, that's pretty much the only way you can finetune with 4GB VRAM.

It might be a good idea to implement `sample_size` as a parameter but 4GB is pretty low nowadays.
