### ISSUE TITLE
RAM Memory error when loading dataset

### ISSUE THREAD

**Issue by ivan-zidov** [minimaxir/gpt-2-simple#73]
Hello there,
I have an issue with finetuning the model. I have dataset in .txt form that has only 850MB and I have 64GB of RAM. After ~10 minute of loading dataset RAM usage spikes up and fills whole 64 GB. Do you have any idea how to fix this problem? Thanks

**Comment by Byest** [comment]
If this is colab, it can handle a max of ~200MB to encode before it runs out of RAM.

If this is your local machine, I think with enough Swap memory, you can do it. I think I've encoded a ~1GB file with 16GB RAM and 125GB Swap, though it took forever. Also, if you aren't already, you'll want to use the gpt2.encode_dataset() method so you only need to encode it once and then pass the .npz file directly into gpt2.finetune().

**Comment by woctezuma** [comment]
Weakly related to #19.

**Comment by ivan-zidov** [comment]
It's not colab, it is local machine
Sometimes it passes loading dataset phase but RAM is 99% in use, and after that 5 seconds peak it lowers back down to 32 GB usage and it is stable while training. 
Btw. thanks for help, i will use encode

**Comment by minimaxir** [comment]
Yes, you'll need to preencode using `gpt2.encode_dataset()`. Fortunately this has the advantage of quickly loading the compresses `.npz` into GPU.

**Comment by Rafcin** [comment]
@Byest how long did it take you to encode the file with the swap?

**Comment by ziqizhang** [comment]
@Rafcin I think trick for encoding is to split your data into smaller, multiple files. Also, Google Colab seems have not problem coping with **encoded data file** larger than the model itself. 

My input data is 10GB, I split it into 100 100MB files, and are able to encode:
- up to 30 (i.e. 3GB raw data) files on a 16GB RAM machine with just 10GB swap
- the entire dataset (i.e., 100 files) on a 128GB RAM machine with no swap (i suspect you don't need that much RAM to do this)

in both, the process took between 1  and 3 hours

The largest encoded file is 4GB, and I successfully fine-tined the 117 model with it on Google Colab. Though the fine tuned model always remains the same size (about 500MB)

Hope that's useful to somebody as this seems to be a common bottleneck to most new users....
