### ISSUE TITLE
Print accuracy

### ISSUE THREAD

**Issue by ikarthikng** [minimaxir/gpt-2-simple#84]
I have been using gpt-2-simple with my own dataset to do some training and I am getting good results. Thank you for creating it. 

I was wondering is there way to print training and validation accuracies during training? I looked through the documentation, I couldn't find anything pointing towards it.

**Comment by ezchx** [comment]
This fork: https://github.com/ezchx/gpt-2-simple includes validation functionality from https://github.com/nshepperd/gpt-2.

**Comment by zymoide** [comment]
> This fork: https://github.com/ezchx/gpt-2-simple includes validation functionality from https://github.com/nshepperd/gpt-2.

Thanks for this. However, if I'm not mistaken, this fork does not include the accuracy metric that @ikarthikng was looking to print during the training process, but rather just the loss.

**Comment by ikarthikng** [comment]
Since it has been more than 4 years. I am going to close this issue.
