### ISSUE TITLE
Trying to use GPT-2-Simple in a GAN environment

### ISSUE THREAD

**Issue by Dormin92** [minimaxir/gpt-2-simple#89]
Hi, and first of all, thanks for making this simplified model of GPT-2. I'm trying to use GPT-2 in a adversarial environment for some research for my masters project and I'm running into a problem loading two models (a generator and a discriminator) at the same time.

I've currently got two models trained on GPT-2-simple using different datasets and I want to load them into my colab notebook. But I'm not sure where exactly the model itself with it's weights and stuff is being stored? I thought it might be in the 'output' variable in load_gpt2(), but apparently you can't run load_gpt2 twice without restarting the runtime.

Here are some links to the resources I'm working off of:
https://towardsdatascience.com/training-gans-using-google-colaboratory-f91d4e6f61fe

Here is the colab notebook I'm using. It is a modified version of the notebook in the above link:
https://colab.research.google.com/drive/1ZneMhu9bnBUHeWjKjWLjtQQqk-in2HRs

I'm sorry if my question here is too general or if I'm being stupid. I'm new to python and machine learning.

**Comment by Dormin92** [comment]
I realize that the whole of the load-gpt2 function is basically using the saver/restore functionality, but I still need to have two models active for a GAN system.

**Comment by minimaxir** [comment]
Text and GANs is pretty much a no-no, and *way* out of scope here.

**Comment by DieseKartoffel** [comment]
Hey Dormin92, nice idea you have there. Did you manage to get your architecture working? I am very interested in doing something similar!

**Comment by Dormin92** [comment]
Sorry, it didn't work out for me, but if you manage to throw something together I'd love to see it!

**Comment by Amnaaftab123** [comment]
hi colab page is not working
