### ISSUE TITLE
Fails to load dataset on Windows due to text encoding

### ISSUE THREAD

**Issue by bob80333** [minimaxir/gpt-2-simple#9]
On Windows 10, when attempting to run this code on my own dataset, I run into this error:

`    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2243891: character maps to <undefined>`

Adding the parameter `encoding='utf8'` to line 33 of load_dataset.py:
`with open(path, 'r') as fp:`
appears to fix this issue.  I'm not 100% sure, because now instead of erroring out immediately, it's using as much RAM as it can

<img width="1306" alt="Screen Shot 2019-04-20 at 6 48 10 PM" src="https://user-images.githubusercontent.com/6364377/56463201-049e2880-639d-11e9-9372-c4450288e18c.png">

I can open a pull request for this if you'd like.

**Comment by minimaxir** [comment]
That's a fair fix, I can add it myself with the work I'm doing on another branch. Thanks!

The all-RAM issue is likely separate. Are you trying to train on a CPU?

**Comment by bob80333** [comment]
No, I have a GTX 1070.  It appears to be happening while still loading my dataset (around 2.2GB of text)

` Loading dataset...
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 14, in <module>
    save_every=500   # how many steps between saving checkpoint
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python37\lib\site-packages\gpt_2_simple\gpt_2.py", line 165, in finetune
    chunks = load_dataset(enc, dataset, combine)
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python37\lib\site-packages\gpt_2_simple\src\load_dataset.py", line 36, in load_dataset
    tokens = np.stack(enc.encode(raw_text))
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\shape_base.py", line 422, in stack
    expanded_arrays = [arr[sl] for arr in arrays]
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\shape_base.py", line 422, in <listcomp>
    expanded_arrays = [arr[sl] for arr in arrays]
MemoryError`

**Comment by minimaxir** [comment]
Hmm, not an expert in how the I/O from RAM to GPU works, and I certainly haven't tested with a 2.2GB file.

Can you get it to run using a smaller dataset? (and making sure the GPU is being utilized)

**Comment by bob80333** [comment]
Alright.  I just tried running it on a dataset of 11.9MB and it loaded the dataset successfully, but then crashed with a new error.  I think my GPU didn't have enough memory

```
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,1023,50257] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node strided_slice_1 (defined at C:\Users\Eric\AppData\Local\Programs\Python\Python37\lib\site-packages\gpt_2_simple\gpt_2.py:115) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.```

**Comment by minimaxir** [comment]
FWIW, when I was running the model via Colaboratory (and `batch_size=1`) it took about 9 GB VRAM; the GTX 1070 has 8 GB VRAM. It's possible consumer GPUs may not be able to run it well, which doesn't make sense as I've seen people train GPT-2 on such GPUs.

**Comment by bob80333** [comment]
I think I'm just hitting the limits of my hardware.  I am using the gpu for the display as well, so that's probably reserving some memory.  I tried with an even smaller dataset (~1MB) and it still ran out of memory, so I assume my GPU just can't hold the model.

**Comment by ahmadalli** [comment]
About the memory issue, I succeeded loading a 100MB dataset on my system with GTX 1070 and 32GB RAM. I has a 2GB dataset and I broke it into 100MB files and fine-tuned the model for each file with `restore_from='latest'` and `overwrite=True` flags
```
