### ISSUE TITLE
Unload and reload different model in same file.

### ISSUE THREAD

**Issue by ThomasWarnasch** [minimaxir/gpt-2-simple#91]
I'm attempting to create a bot that autocompletes people prompts, to do so I'm running 
`sess = gpt2.start_tf_sess()`
outside of the input loop and the separately trained models inside
`if model1:`
`    gpt2.load_gpt2(sess, run_name='run1')`
`        Text = gpt2.generate(sess,`
`              length=700,`
`              temperature=0.7,`
`              prefix=stringdata,`
`            include_prefix=False,`
`            nsamples=1,`
`              batch_size=1`
 `             )`
`        print(Text)`
but when running loop with a different run_name to try and load a different model it is unable to load the new model. Is there any way to unload the model without restarting the script?

**Comment by woctezuma** [comment]
#80
