### ISSUE TITLE
Finetune Json Issue

### ISSUE THREAD

**Issue by Rafcin** [minimaxir/gpt-2-simple#97]
When running any of the text files I created the program complains about the following issue regardless of the text file.

`
sess = gpt2.start_tf_sess()
gpt2.finetune(sess,
              'java_train_java.txt',
              model_name=model_name,
              steps=1000)   # steps is max number of training steps
`
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-7-a5d62de07900> in <module>
      6               'java_train_java.txt',
      7               model_name=model_name,
----> 8               steps=1000)   # steps is max number of training steps

~/.local/lib/python3.5/site-packages/gpt_2_simple/gpt_2.py in finetune(sess, dataset, steps, model_name, model_dir, combine, batch_size, learning_rate, accumulate_gradients, restore_from, run_name, checkpoint_dir, sample_every, sample_length, sample_num, save_every, print_every, max_checkpoints, use_memory_saving_gradients, only_train_transformer_layers, overwrite)
    153                 raise(fnf_error)
    154 
--> 155     enc = encoder.get_encoder(checkpoint_path)
    156     hparams = model.default_hparams()
    157     with open(os.path.join(checkpoint_path, 'hparams.json')) as f:

~/.local/lib/python3.5/site-packages/gpt_2_simple/src/encoder.py in get_encoder(checkpoint_path)
    108 def get_encoder(checkpoint_path):
    109     with open(os.path.join(checkpoint_path, 'encoder.json'), 'r') as f:
--> 110         encoder = json.load(f)
    111     with open(os.path.join(checkpoint_path, 'vocab.bpe'), 'r', encoding="utf-8") as f:
    112         bpe_data = f.read()

/usr/lib/python3.5/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    266         cls=cls, object_hook=object_hook,
    267         parse_float=parse_float, parse_int=parse_int,
--> 268         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    269 
    270 

/usr/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    317             parse_int is None and parse_float is None and
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:
    321         cls = JSONDecoder

/usr/lib/python3.5/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.5/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by woctezuma** [comment]
Make sure the JSON file is not faulty and can be accessed from the Google virtual machine.

**Comment by Rafcin** [comment]
I'll try that and let you know, thanks!

**Comment by Rafcin** [comment]
I redownload the model and it persists to throw the error

**Comment by woctezuma** [comment]
What is your work environment? You work in a Google Colab session?

**Comment by Rafcin** [comment]
Same issue with the example from above. Also I should note that im running this in a Google Cloud J-Notebook

**Comment by Rafcin** [comment]
One possibility would be to use Pandas using the read json function
`pandas.read_json()`

**Comment by Rafcin** [comment]
actually disregard what I wrote I wasn't thinking. Also I attempted to read the encoder file, it complains that `Unexpected token < in JSON at position 0`

**Comment by Rafcin** [comment]
I inspected each file they have written 
`<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: gpt-2/models/345/checkpoint</Details></Error>`

**Comment by Rafcin** [comment]
I'm a fool.... I wrote 345 not 345M ... case closed. Sorry about this then...

**Comment by Rafcin** [comment]
Although one question is it required to use a GPU to train the model say if I pass a 1.8gb txt file to it?

**Comment by woctezuma** [comment]
> Although one question is it required to use a GPU to train the model say if I pass a 1.8gb txt file to it?

I think so. Especially with that big of a text file.

**Comment by Viole-Grace** [comment]
A Finetuning session for the same model does this.

A simple workaround is to add
`import tensorflow as tf`
`tf.reset_default_graph()`
before your `gpt2.finetune(..)`

sample code:

`
.
.
.
def generate(input_file_name, nsamples=5000, model="124M"):

    import tensorflow as tf
    tf.reset_default_graph()

    if not os.path.isdir(os.path.join("models","124M")):
        print("Downloading the model : 124M pretrained, 500M final tuning")
        gpt2.download_gpt2(model_name="124M")
.
.
.

`
