### ISSUE TITLE
Error using the 345M model

### ISSUE THREAD

**Issue by anamariamocanu** [minimaxir/gpt-2-simple#99]
Hello,

I get this error only when I use the 345M model (using the 117 model works fine):
InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Anything I'm doing wrong? Is it related to Update for 345M #23?

Thanks!
Ana

**Comment by woctezuma** [comment]
Could it be that you are trying to fine-tune with the 345M model from a checkpoint previously fine-tuned with the 117M model?

**Comment by anamariamocanu** [comment]
Thank you @woctezuma, indeed that's what happened. I set up 2 runs for each model
